mod 'boxen',    '3.11.0', :github_tarball => 'boxen/puppet-boxen'
mod 'module-data','0.0.4', :github_tarball => "ripienaar/puppet-module-data"
mod 'homebrew', '2.0.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',   '4.8.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'xquartz',  '1.2.1', :github_tarball => 'boxen/puppet-xquartz'
